"""add operation column to item_pf_id

Revision ID: 1d2f7187853b
Revises: ecee1d927379
Create Date: 2025-04-04 13:29:57.512210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2f7187853b'
down_revision: Union[str, None] = 'ecee1d927379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('item_pf_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'item_pf_id')
    # ### end Alembic commands ###
