"""Add photo_file_ids to order_items

Revision ID: 642ab6234cda
Revises: 6b4c06f61650
Create Date: 2025-05-06 22:53:37.131613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642ab6234cda'
down_revision: Union[str, None] = '6b4c06f61650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('photo_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'photo_file_ids')
    # ### end Alembic commands ###
