"""Add touch_or_backlight to order_items

Revision ID: 6b4c06f61650
Revises: d14bc69d0739
Create Date: 2025-05-06 21:47:06.434626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4c06f61650'
down_revision: Union[str, None] = 'd14bc69d0739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('touch_or_backlight', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'touch_or_backlight')
    # ### end Alembic commands ###
