"""Add task_id to OrderItem

Revision ID: ab2598e753e3
Revises: 19608d0df46c
Create Date: 2025-04-01 13:41:27.752894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2598e753e3'
down_revision: Union[str, None] = '19608d0df46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('task_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'task_id')
    # ### end Alembic commands ###
