"""Add     assembly_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False) to order_items

Revision ID: d03725045526
Revises: 642ab6234cda
Create Date: 2025-05-09 12:30:45.219055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03725045526'
down_revision: Union[str, None] = '642ab6234cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('assembly_required', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'assembly_required')
    # ### end Alembic commands ###
