"""Add photo_file_ids to carts

Revision ID: d14bc69d0739
Revises: 51aa5836915f
Create Date: 2025-05-01 12:36:44.364040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd14bc69d0739'
down_revision: Union[str, None] = '51aa5836915f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('photo_file_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'photo_file_ids')
    # ### end Alembic commands ###
